// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cagormlkndkzhtsiavie.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNhZ29ybWxrbmRremh0c2lhdmllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzOTk5NzUsImV4cCI6MjA3MTk3NTk3NX0.KD8OKsCHafufuR02uD7ULVU2xKvve5J2jgmTLwU3RyY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});